In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [3]:
# Load the dataset
df = pd.read_excel('Road.xlsx')

In [4]:
# Check for missing values
print(df.isnull().sum())

# Handle missing values by forward-filling
df.ffill(inplace=True)

Time                              0
Day_of_week                       0
Age_band_of_driver                0
Sex_of_driver                     0
Educational_level               292
Vehicle_driver_relation         203
Driving_experience              332
Type_of_vehicle                 410
Owner_of_vehicle                193
Service_year_of_vehicle        1661
Defect_of_vehicle              1841
Area_accident_occured            99
Lanes_or_Medians                168
Road_allignment                  54
Types_of_Junction                 0
Road_surface_type                69
Road_surface_conditions           0
Light_conditions                  0
Weather_conditions                0
Type_of_collision                55
Number_of_vehicles_involved       0
Number_of_casualties              0
Vehicle_movement                 95
Casualty_class                    0
Sex_of_casualty                   0
Age_band_of_casualty              0
Casualty_severity                 0
Work_of_casuality           

In [5]:
from sklearn.preprocessing import LabelEncoder

label_encoders = {}
for column in df.select_dtypes(include=['object']).columns:
    le = LabelEncoder()
    df[column] = le.fit_transform(df[column].astype(str))
    label_encoders[column] = le

In [6]:
# Select relevant features based on domain knowledge
features = ['Age_band_of_driver', 'Sex_of_driver', 'Educational_level', 'Driving_experience', 
            'Type_of_vehicle', 'Road_surface_type', 'Road_surface_conditions', 'Light_conditions', 
            'Weather_conditions', 'Type_of_collision', 'Number_of_vehicles_involved', 
            'Number_of_casualties', 'Vehicle_movement', 'Casualty_class', 'Sex_of_casualty', 
            'Age_band_of_casualty', 'Casualty_severity']

X = df[features]
y = df['Accident_severity']

In [7]:
# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [8]:
# Standardize the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [9]:
# Initialize the KNN classifier
knn = KNeighborsClassifier(n_neighbors=5)

# Train the model
knn.fit(X_train, y_train)

KNeighborsClassifier()

In [10]:
# Make predictions
y_pred = knn.predict(X_test)

# Evaluate the model
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

print("\nAccuracy Score:")
print(accuracy_score(y_test, y_pred))

Confusion Matrix:
[[   1    0    0    1    0   19]
 [   0    0    0    0    0    2]
 [   0    0    0    1    0   10]
 [   0    0    1    1    0  197]
 [   0    0    0    0    0    4]
 [   3    0    0   24    0 1236]]

Classification Report:
              precision    recall  f1-score   support

           0       0.25      0.05      0.08        21
           1       0.00      0.00      0.00         2
           2       0.00      0.00      0.00        11
           3       0.04      0.01      0.01       199
           4       0.00      0.00      0.00         4
           5       0.84      0.98      0.91      1263

    accuracy                           0.83      1500
   macro avg       0.19      0.17      0.17      1500
weighted avg       0.72      0.83      0.76      1500


Accuracy Score:
0.8253333333333334


c:\Users\beher\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)
c:\Users\beher\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\beher\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-d

In [11]:
from sklearn.inspection import permutation_importance

result = permutation_importance(knn, X_test, y_test, n_repeats=10, random_state=42)
importance = result.importances_mean

for i, imp in enumerate(importance):
    print(f"Feature {features[i]}: {imp}")

c:\Users\beher\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)
c:\Users\beher\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdim

Feature Age_band_of_driver: 0.000466666666666693
Feature Sex_of_driver: -0.00039999999999995595
Feature Educational_level: -0.0009333333333332971
Feature Driving_experience: -0.0023333333333332984
Feature Type_of_vehicle: -0.0009333333333332971
Feature Road_surface_type: 0.00013333333333336305
Feature Road_surface_conditions: -6.666666666662601e-05
Feature Light_conditions: -0.003599999999999948
Feature Weather_conditions: 0.0003333333333333854
Feature Type_of_collision: -0.00426666666666663
Feature Number_of_vehicles_involved: -0.0016666666666666386
Feature Number_of_casualties: 0.0015333333333333865
Feature Vehicle_movement: -0.0002666666666666262
Feature Casualty_class: 0.00033333333333337436
Feature Sex_of_casualty: -0.001399999999999968
Feature Age_band_of_casualty: 0.00040000000000004474
Feature Casualty_severity: 4.4408920985006264e-17


c:\Users\beher\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [11]:
import joblib

# Save the model
joblib.dump(knn, 'knn_road_accident_model.pkl')

# Load the model
# loaded_model = joblib.load('knn_road_accident_model.pkl')

['knn_road_accident_model.pkl']

In [12]:
# Save the predictions to a CSV file
df_results = pd.DataFrame({
    'Actual_Severity': y_test,
    'Predicted_Severity': y_pred
})

df_results.to_csv('predictions.csv', index=False)
print("Predictions saved successfully!")


Predictions saved successfully!


In [13]:
feature_importance_df = pd.DataFrame({
    'Feature': features,
    'Importance': importance
})
feature_importance_df.to_csv('feature_importance.csv', index=False)
